Allow shorter node pool ids for scale
civo/cli-go pull request #160
Opened 2021-10-21 06:27 UTC by avinashupadhya99

Fixes #158 

Changes - 
- [x] When deleting nodepool, keep strings.Contains usage. Check the length to be at least 6 characters
- [x] When scaling nodepool, implement strings.Contains and check the length to be at least 6 characters
- [x] When user provides short nodepool ID (<6), exit the CLI and ask user to provide an ID with at least 6 characters
- [x] Print full node pool ID after create, scale and delete operations on the node pool

2021-10-21 13:41 UTC, avinashupadhya99 commented
@zulh-civo PR is ready for review. Thanks!

2021-10-25 04:25 UTC, zulh-civo requested changes

2021-10-25 04:25 UTC, zulh-civo commented on README.md
> +You can scale a pool in your cluster, while the cluster is running. It takes the name of the cluster (or the ID), the pool ID (min. 6 characters), and `--nodes` which is the new number of nodes in th
Instead of `min. 6 characters`, can we say `at least 6 characters`?

2021-10-25 04:25 UTC, zulh-civo commented on README.md
> +You can delete a pool in your cluster. It takes the name of the cluster (or the ID) and the pool ID (min. 6 characters)
Instead of `min. 6 characters`, can we say `at least 6 characters`?

2021-10-25 04:25 UTC, zulh-civo commented on cmd/kubernetes_nodepool_delete.go
> +				utility.Error("Please provide the node pool ID with atleast 6 characters for %s", v.Name)
Small nit — can we make it `at least` instead of `atleast`?

2021-10-25 04:25 UTC, zulh-civo commented on cmd/kubernetes_nodepool_scale.go
> +			utility.Error("Please provide the node pool ID with atleast 6 characters for %s", nodePoolID)
Small nit — can we make it `at least` instead of `atleast`?

2021-10-25 04:25 UTC, zulh-civo commented on cmd/kubernetes_nodepool_delete.go
>  			}
Tbh, I don't quite get why we need to set `kubernetesPoolNameList` to `nil` here and set the value again by taking the second return value from the `RemoveNodePool` function.

We already have [this](https://github.com/civo/cli/blob/ce48750f6d40af97bb3a1b312899da91acf44848/cmd/kubernetes_nodepool_delete.go#L48-L51) and I think that's already enough. If I missed anything here, please enlighten me and provide examples.

2021-10-25 04:25 UTC, zulh-civo commented on utility/kubernetes.go
> +func RemoveNodePool(s []civogo.KubernetesClusterPoolConfig, id string, names []string) ([]civogo.KubernetesClusterPoolConfig, []string) {
Related to my comment in _cmd/kubernetes_nodepool_delete.go_ file, I think we don't need `names` here. I also think we don't need the second return value. If I failed to understand what's going on here or unable to see what potentially goes wrong with the current implementation (in `master` branch), please explain.

2021-10-25 05:13 UTC, avinashupadhya99 commented on cmd/kubernetes_nodepool_delete.go
>  			}
The reason why the `kubernetesPoolNameList` is reinitialized is to get the complete node pool ID to maintain the consistency with the other node pool commands

2021-10-25 06:21 UTC, zulh-civo commented on cmd/kubernetes_nodepool_delete.go
>  			}
Thanks for the clarification

2021-10-25 06:22 UTC, zulh-civo approved these changes

2021-10-25 06:23 UTC, zulh-civo commented
@avinashupadhya99 could you rebase your branch on top of civo/cli master branch?

2021-10-25 07:00 UTC, avinashupadhya99 commented
> @avinashupadhya99 could you rebase your branch on top of civo/cli master branch?

Sorry, looks like the commits were repeated during rebase. I should have stuck to merging. Do you want me to do a hard reset on the new commits and do a merge again? Sorry about this

2021-10-25 07:19 UTC, zulh-civo commented
That's fine. I'll squash all the commits.

2021-10-25 07:19 UTC, merged