fix: reconsider behavior when providing a value lower than 500 for bu…
civo/cli-go pull request #438
Opened 2024-07-09 22:42 UTC by harsh082ip

As mentioned in issue #394, the following changes have been made:

The command will now fail immediately for values less than 500 GB with an appropriate error message.

Introduced a --yes flag to automatically adjust the bucket size to the nearest multiple of 500 without prompting the user. 
For example:
Warning: The size to create an object store must be a multiple of 500. Would you like to create an object store of 1000 GB instead? (y/n)?
Using the --yes flag, users can bypass this prompt.

Improved the help message to make the minimum and default size requirements explicit:
  -s, --size int                  Size of the Object store in GB (minimum: 500)  (default 500)

Please review and let me know if any changes are needed.

2024-07-10 09:40 UTC, harsh082ip commented
Got it

2025-05-06 14:27 UTC, alessandroargentieri commented
@fulviodenza are you free to give it a look?

2025-05-06 14:36 UTC, giornetta commented
Hi @harsh082ip, thanks for your contribution!

While the original issue has already been marked as closed and some parts of it were resolved, I think we should discuss whether we want to let the `--yes` flag automatically select an higher size in this context.
This could cause some confusion among customers and some churn when they receive an higher bill than they expected.

 @alessandroargentieri @fulviodenza @uzaxirr thoughts?

2025-05-06 14:42 UTC, harsh082ip commented
Hii @giornetta ,

Thanks for the context! I agree, auto-selecting a higher size with --yes might lead to unexpected charges. Happy to align on the best approach.

2025-05-06 14:45 UTC, fulviodenza requested changes

2025-05-06 14:45 UTC, fulviodenza commented on cmd/objectstore/objectstore.go
> +	objectStoreCreateCmd.Flags().Int64VarP(&bucketSize, "size", "s", 500, "Size of the Object store in GB (minimum: 500)")
let's use a variable for this `500` value,

2025-05-06 14:45 UTC, fulviodenza commented on cmd/objectstore/objectstore_create.go
> +					os.Exit(0)
this indicates success, the operation, when not accepted is not a success, we need `os.Exit(1)` for this

2025-05-06 14:45 UTC, fulviodenza commented on cmd/objectstore/objectstore_create.go
> +				utility.YellowConfirm("The size to create an object store must be a multiple of 500. Would you like to create an %s of %d GB instead? (y/n) ? ", utility.Green("object store"), bucketSize+(500-buc
we should specify that 500 and 1000GB are the only allowed sizes

2025-05-06 14:51 UTC, fulviodenza commented on cmd/objectstore/objectstore_create.go
> +				utility.YellowConfirm("The size to create an object store must be a multiple of 500. Would you like to create an %s of %d GB instead? (y/n) ? ", utility.Green("object store"), bucketSize+(500-buc
`bucketSize+(500-bucketSize%500))` could be a small function

2025-06-28 05:05 UTC, harsh082ip commented
Hi @fulviodenza, apologies for the delay — I've pushed the required changes. Let me know if anything else is needed.

2025-06-28 11:36 UTC, fulviodenza commented on cmd/objectstore/objectstore.go
> +	objectStoreCreateCmd.Flags().Int64VarP(&bucketSize, "size", "s", minBucketSizeGB, fmt.Sprintf("Size of the Object store (Allowed sizes: %dGB or 1000GB)", minBucketSizeGB))
why the 500 is set as constant while the 1000 isn't?

2025-06-28 11:36 UTC, fulviodenza commented on cmd/objectstore/objectstore_create.go
> +	Long:    "Bucket size should be in Gigabytes (GB) and must be either 500 or 1000.\n",
couldn't we use the constants of before, declared in a common package?

2026-05-12 08:40 UTC, giornetta commented
Closing as stale, no activity on this since June of last year.

2026-05-12 08:40 UTC, closed without merging